### ISSUE TITLE
Failed to recognize mod

### ISSUE THREAD

**Issue by daxpedda** [Spoons/rmm#15]
**Description**
I `sync`ed the mod ["Fridges Are Hoppers"](https://steamcommunity.com/sharedfiles/filedetails/?id=2894860548). But when using `update` it says that it's ignoring it.

I suspect the issue is the authors name, because usually when you `sync` mods the folder gets renamed to `author.mod`, which in this case it didn't, it just staid as `2894860548`.

**Reproduction**
List the steps to reproduce the issue. Ex:
1. `rmm sync "Fridges Are Hoppers"`
2. `rmm update`

**Info**
OS: Manjaro XFCE
RMM: 1.0.16.dev3
RimWorld: 1.4.3704 rev896

**Comment by daxpedda** [comment]
Strangely, I also found that ["Hemogen Cuisine"](https://steamcommunity.com/sharedfiles/filedetails/?id=2933693918) is also not recognized. The authors name and it's mod is just ASCII.

**Comment by Spoons** [comment]
Thanks. Taking a look at this now.

**Comment by Spoons** [comment]
Issue was that those mods had a lower case 'about.xml' versus a 'About.xml'.

Fixed and pushed.
