### ISSUE TITLE
Mod is downloaded to the wrong path

### ISSUE THREAD

**Issue by NikitaBel228** [Spoons/rmm#16]
**Description**
This is a duplicate of #6, which is supposedly solved 

**Reproduction**
1. Try downloading any mod with `rmm sync`
2. After a successful download, get an error that the path is invalid
`Success. Downloaded item 2950258180 to "/tmp/rmm-njy308k3/.steam/SteamApps/workshop/content/294100/2950258180" (1199699 bytes)`
*a bunch of errors*
`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/rmm-njy308k3/Steam/steamapps/workshop/content/294100'
`

**Info**
OS: Linux CachyOS
RMM version: 1.0.16.dev3 (downloaded from AUR rmm-git)
RimWorld version: 1.4.3704

**Comment by Spoons** [comment]
Just fixed this. Changes are on the git repo and aur. Will publish to pypi tomorrow.

**Comment by Spoons** [comment]
New version posted. Let me know if it wasn't solved for you!
