### ISSUE TITLE
Crash at empty "author" tag

### ISSUE THREAD

**Issue by canisdirusleidy** [Spoons/rmm#17]
**Description**
When trying to execute any command, python crashes with the stack trace and message "TypeError: can only join an iterable"

**Reproduction**
1. Install [this mod ](https://github.com/kittycat2002/rimworld-showhair)or any other where the "author" tag in About.xml looks like this: `<author></author>`
2. Run rmm.

**Info**
OS: Devuan Ceres
RMM: 1.0.15

**Comment by Spoons** [comment]
Just fixed this. I have not pushed the changes yet to pypi but they are in git and on the AUR.

Will close once I publish to PyPi.

**Comment by Spoons** [comment]
New version uploaded. I'm going to close this but do let me know if it doesn't work for you.
