### ISSUE TITLE
[Linux] [Workaround aviable] Downloading a mod fails, the path is wrong

### ISSUE THREAD

**Issue by HonzoNebro** [Spoons/rmm#6]
When downloading a mod from the workshop with RMM, when trying to move it to the game folder it crashes because the path is wrong

`Connecting anonymously to Steam Public...OK

Waiting for client config...OK

Waiting for user info...OK

Downloading item 2202185773 ...

Success. Downloaded item 2202185773 to "/tmp/**rmm-7hc2cik5/Steam/steamapps/workshop/content**/294100/2202185773" (791381 bytes) Traceback (most recent call last):

  File "/home/honzo/.local/bin/rmm", line 8, in <module>
    sys.exit(run())

...[several more errors]...
FileNotFoundError: [Errno 2] No such file or directory: '/tmp**/rmm-7hc2cik5/.steam/steamapps/workshop/content**/294100'
`
Notice the correct path of the download is .../Steam/steamapps/workshop/... and not .../.steam/steamapps/workshop/...

Anyway, you can manually copy the downloaded mod to the Mods folder of the game

**Comment by Spoons** [comment]
Are you using MacOS or Linux?

**Comment by Spoons** [comment]
That is unusual. SteamCMD is largely a black box. In my experience, steamcmd should place files in `/tmp-identifier/.steam/steamapps/workshop/content` not `/tmp-ident/Steam/steamapps/workshop/content`.

Frankly, I have no idea why this is happening for you. It's probably not worth the time to trace the binary. However, I'll create a patch that detects this behavior. It might take me a minute.

**Comment by Spoons** [comment]
Hey, sorry about the delay. I've pushed a change which should fix this issue for you! Let me know if it does not.

**Comment by NikitaBel228** [comment]
Somehow I have the opposite issue:
`Success. Downloaded item 2910865748 to "/tmp/rmm-7eo2d0ur/.steam/SteamApps/workshop/content/294100`
`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/rmm-7eo2d0ur/Steam/steamapps/workshop/content/294100'`
